spring:
  application:
    name: demomic-license
  config:
    import: optional:configserver:http://demomic-config:9000
  jpa.hibernate.ddl-auto: create-drop

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone:
        http://demomic-eureka:8070/eureka/

resilience4j:
  circuitbreaker:
    instances:
      demomic-license:
        sliding-window-size: 5
        wait-duration-in-open-state: 10s
        slow-call-duration-threshold: 3s
        failure-rate-threshold: 10


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "health,env,refresh"